os: osx
language: swift
osx_image: xcode10.1
xcode_project: ApolloDeveloperKit.xcodeproj
xcode_scheme: ApolloDeveloperKit

cache:
  bundler: true
  directories:
    - Carthage/Build

stages:
  - name: test
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - &test
      stage: test
      install: carthage build --platform iOS --no-use-binaries --cache-builds
      xcode_destination: "OS=12.1,name=iPhone XS"
      name: iOS 12.1
    - <<: *test
      xcode_destination: "OS=11.4,name=iPhone 5s"
      name: iOS 11.4
      before_script: |
        gem install slather -v '~> 2.4.7'
        curl -LSso cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-darwin-amd64
        chmod +x cc-test-reporter
        ./cc-test-reporter before-build
      after_script: |
        slather coverage -tx --scheme="$TRAVIS_XCODE_SCHEME" "$TRAVIS_XCODE_PROJECT"
        ./cc-test-reporter after-build -t cobertura --exit-code $TRAVIS_TEST_RESULT
    - name: pod trunk push
      stage: deploy
      install: gem install cocoapods -v '~> 1.7.3'
      script: |
        set -exo pipefail
        pod trunk push --verbose --allow-warnings | tee pod.log | sed 's/.*/./g' | tr -d '\n'
      after_failure: fgrep error pod.log
