source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 10

target 'ApolloDeveloperKitInstallTests-CocoaPods' do
  use_frameworks!

  pod 'Apollo', podspec: 'https://raw.githubusercontent.com/CocoaPods/Specs/ed9a450c259e9a00814930bc5c03badd86935c4c/Specs/a/6/c/Apollo/0.31.0/Apollo.podspec.json'
  pod 'ApolloDeveloperKit', path: '../'
end
