#!/bin/bash

show_help() {
    cat <<-EOS
Usage: boot-simulator [-h] [-d] <IDENTIFIER>

Options:
    -h, --help         Show this help and exit
    -d, --destination  Interpret IDENTIFIER as xcodebuild's destination

Arguments:
    <IDENTIFIER>       Device identifier or destination (when -d option is given)
EOS
}

identifier=
destination=0
while [ $# -gt 0 -a -z "$identifier" ]
do
    case "$1" in
        -h|--help)
            show_help
            exit
            ;;
        -d|--destination)
            destination=1
            shift
            ;;
        -*)
            echo "error: unrecognized option $1." >&2
            show_help >&2
            exit 1
            ;;
        *)
            identifier="$1"
            shift
            ;;
    esac
done
if [ -z "$identifier" ]; then
    echo 'error: too few arguments.' >&2
    show_help >&2
fi
if [ $# -ne 0 ]; then
    echo 'error: too many arguments.' >&2
    show_help >&2
fi

if [ $destination -ne 0 ]; then
    os="$(echo "$identifier" | grep -oE 'OS=[0-9]*\.[0-9]*' | cut -f2 -d=)"
    name="$(echo "$identifier" | grep -oE 'name=[^,]*' | cut -f2 -d=)"
    identifier="$(xcrun simctl list | awk "/^-- .* --$/{if (in_range) exit} /^-- iOS $os --$/{in_range=1; next} in_range&&/$name \(/" | awk -F'[()]' '{print $2}')"
fi
xcrun simctl boot "$identifier"
